=== nebula-plugins/gradle-resolution-rules/src/test/resources/valid-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Resolution Rule",
  "description": "validation of resolution rules",
  "type": "object",
  "properties": {
    "align": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "group": {
            "type": "string"
          },
          "includes": {
            "type": "array"
          },
          "excludes": {
            "type": "array"
          },
          "match": {
            "type": "string"
          },
          "ruleSet": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        },
        "required": [
          "includes",
          "excludes",
          "reason",
          "author",
          "date",
          "group"
        ],
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "deny": {
      "type": "array"
    },
    "exclude": {
      "type": "array"
    },
    "reject": {
      "type": "array"
    },
    "replace": {
      "type": "array"
    },
    "substitute": {
      "type": "array"
    }
  },
  "required": [
    "align",
    "deny",
    "exclude",
    "reject",
    "replace",
    "substitute"
  ],
  "additionalProperties": false
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-servo.json
{
  "align": [
    {
      "name": "align-servo",
      "group": "com\\.netflix\\.servo",
      "includes": [],
      "excludes": ["servo-internal", "servo-cloudwatch", "servo"],
      "reason": "Align Servo libraries.",
      "author": "Steve Hill <sghill.dev@gmail.com>",
      "date": "2018-07-28"
    }
  ],
  "replace": [],
  "substitute": [],
  "deny": [],
  "reject": [],
  "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-spring.json
{
    "align": [
        {
            "group": "org\\.springframework",
            "includes": ["spring-(tx|aop|instrument|context-support|beans|jms|test|core|oxm|web|context|expression|aspects|websocket|framework-bom|webmvc|webmvc-portlet|jdbc|orm|instrument-tomcat|messaging)"],
            "excludes": [],
            "match": "[2-9]\\.[0-9]+\\.[0-9]+.RELEASE",
            "reason": "Align Spring",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-05-16"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-retrofit2.json
{
    "align": [
            {
                "name": "align-retrofit2",
                "group": "com\\.squareup\\.retrofit2",
                "includes": [],
                "excludes": [],
                "reason": "Align retrofit2",
                "author": "Steve Hill <sghill.dev@gmail.com>",
                "date": "2018-05-19"
            }
    ],
    "replace": [],
    "substitute": [],
    "exclude": [],
    "deny": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-groovy.json
{
    "align": [
            {
                "name": "align-groovy",
                "group": "org\\.codehaus\\.groovy",
                "includes": [],
                "excludes": ["groovy-(eclipse-compiler|eclipse-batch|all-tests|xmlrpc|all-jdk14|jdk14|all-minimal)", "http-builder"],
                "reason": "Align Groovy libraries.",
                "author": "Danny Thomas <dannyt@netflix.com>",
                "date": "2016-06-01"
            }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-asm.json
{
  "align": [
    {
      "name": "align-asm",
      "group": "org\\.ow2\\.asm",
      "includes": [],
      "excludes": [
        "asm-all",
        "asm-debug-all",
        "asm-parent"
      ],
      "reason": "Align asm libraries.",
      "author": "Steve Hill <sghill.dev@gmail.com>",
      "date": "2018-07-28"
    }
  ],
  "replace": [],
  "substitute": [],
  "deny": [],
  "reject": [],
  "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-hibernate-core.json
{
  "align": [
    {
      "name": "align-hibernate-core",
      "group": "org\\.hibernate",
      "includes": [
        "hibernate-agroal",
        "hibernate-c3p0",
        "hibernate-core",
        "hibernate-ehcache",
        "hibernate-entitymanager",
        "hibernate-envers",
        "hibernate-gradle-plugin",
        "hibernate-hikaricp",
        "hibernate-infinispan",
        "hibernate-java8",
        "hibernate-jcache",
        "hibernate-jipijapa",
        "hibernate-jpamodelgen",
        "hibernate-orm-jbossmodules",
        "hibernate-osgi",
        "hibernate-proxool",
        "hibernate-spatial",
        "hibernate-testing",
        "hibernate-tools",
        "hibernate-tools-maven-plugin",
        "hibernate-tools-parent",
        "hibernate-vibur"
      ],
      "excludes": [],
      "reason": "Align hibernate-core libraries.",
      "author": "Steve Hill <sghill.dev@gmail.com>",
      "date": "2018-07-28"
    }
  ],
  "replace": [],
  "substitute": [],
  "deny": [],
  "reject": [],
  "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-spectator.json
{
    "align": [
        {
            "name": "align-spectator",
            "group": "com\\.netflix\\.spectator",
            "includes": [],
            "excludes": ["spectator-reg-metrics2", "spectator-reg-tdigest"],
            "reason": "Align Spectator libraries.",
            "author": "Brian Harrington <brharrington@netflix.com>",
            "date": "2016-07-09"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-spring-integration.json
{
    "align": [
        {
            "name": "align-springframework-integration",
            "group": "org\\.springframework\\.integration",
            "includes": [],
            "excludes": ["spring-integration-(smb|java-dsl|kafka|tuple|cassandra|flow|smpp|splunk|httpinvoker|parent|adapter|samples|aws)"],
            "reason": "Align Spring Integration",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-05-16"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}
