=== nebula-plugins/gradle-resolution-rules/src/test/resources/valid-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Resolution Rule",
  "description": "validation of resolution rules",
  "type": "object",
  "properties": {
    "align": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "group": {
            "type": "string"
          },
          "includes": {
            "type": "array"
          },
          "excludes": {
            "type": "array"
          },
          "match": {
            "type": "string"
          },
          "ruleSet": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        },
        "required": [
          "includes",
          "excludes",
          "reason",
          "author",
          "date",
          "group"
        ],
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "deny": {
      "type": "array"
    },
    "exclude": {
      "type": "array"
    },
    "reject": {
      "type": "array"
    },
    "replace": {
      "type": "array"
    },
    "substitute": {
      "type": "array"
    }
  },
  "required": [
    "align",
    "deny",
    "exclude",
    "reject",
    "replace",
    "substitute"
  ],
  "additionalProperties": false
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/optional-slf4j-bridge.json
{
    "substitute": [
        {
            "module": "commons-logging:commons-logging",
            "with": "org.slf4j:jcl-over-slf4j:1.7.+",
            "reason": "Subsitute Commons Logging with SLF4J bridge",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-04-28T22:31:14.321Z"
        },
        {
            "module": "log4j:log4j",
            "with": "org.slf4j:log4j-over-slf4j:1.7.+",
            "reason": "Subsitute log4j with SLF4J bridge",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-04-28T22:31:14.321Z"
        }
    ],
    "replace": [],
    "align": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-xbean.json
{
    "align": [
        {
            "name": "align-xbean",
            "group": "org\\.apache\\.xbean",
            "includes": ["xbean-finder-shaded", "xbean-telnet", "xbean-blueprint", "xbean-reflect", "xbean-asm5-shaded", "xbean-naming", "xbean-finder", "xbean-asm-util", "xbean-bundleutils", "xbean-classpath", "xbean-classloader", "maven-xbean-plugin", "xbean-spring", "xbean"],
            "excludes": [],
            "reason": "Align xbean libraries.",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-05-16"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-hibernate-validator.json
{
  "align": [
    {
      "name": "align-hibernate-validator",
      "group": "org\\.hibernate",
      "includes": ["hibernate-validator", "hibernate-validator-.*"],
      "excludes": [],
      "reason": "Align hibernate-validator libraries.",
      "author": "Steve Hill <sghill.dev@gmail.com>",
      "date": "2018-07-28"
    }
  ],
  "replace": [],
  "substitute": [],
  "deny": [],
  "reject": [],
  "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-hibernate-search.json
{
  "align": [
    {
      "name": "align-hibernate-search",
      "group": "org\\.hibernate",
      "includes": ["hibernate-search", "hibernate-search-.*"],
      "excludes": [],
      "reason": "Align hibernate-search libraries.",
      "author": "Steve Hill <sghill.dev@gmail.com>",
      "date": "2018-07-28"
    }
  ],
  "replace": [],
  "substitute": [],
  "deny": [],
  "reject": [],
  "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/replace-google-collections.json
{
    "replace" : [
            {
                "module" : "com.google.collections:google-collections",
                "with" : "com.google.guava:guava",
                "reason" : "Google Collections was superceded by Guava",
                "author" : "Danny Thomas",
                "date" : "2016-04-26T00:00:00.000Z"
            }
    ],
    "align": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-jackson.json
{
    "align": [
            {
                "name": "align-jackson",
                "group": "com\\.fasterxml\\.jackson\\.(core|dataformat|datatype|jaxrs|jr|module)",
                "excludes": ["jackson-datatype-jdk7", "jackson-module-scala_2.12", "jackson-module-scala_2.12.0-RC1", "jackson-module-scala_2.12.0-M5", "jackson-module-scala_2.12.0-M4", "jackson-module-scala_2.11", "jackson-module-scala_2.10", "jackson-module-scala_2.9.3", "jackson-module-scala_2.9.2", "jackson-module-scala_2.9.1", "jackson-module-swagger", "jackson-module-scala", "jackson-datatype-hibernate", "jackson-dataformat-ion"],
                "includes": [],
                "reason": "Align all Jackson libraries",
                "match": "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)?(\\.pr\\d+)?",
                "author": "Danny Thomas <dannyt@netflix.com>",
                "date": "2016-05-19"
            }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/optional-spring-boot-log4j2.json
{
    "substitute": [],
    "replace": [
        {
            "module" : "commons-logging:commons-logging",
            "with" : "org.springframework:spring-jcl",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "ch.qos.reload4j:reload4j",
            "with" : "org.apache.logging.log4j:log4j-1.2-api",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "org.slf4j:slf4j-reload4j",
            "with" : "org.apache.logging.log4j:log4j-slf4j2-impl",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Asi Bross",
            "date" : "2025-05-30"
        }
    ],
    "align": [],
    "deny": [],
    "exclude": [
        {
            "module" : "org.apache.logging.log4j:log4j-to-slf4j",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "org.slf4j:slf4j-nop",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "org.slf4j:slf4j-simple",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "org.slf4j:slf4j-log4j12",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "org.slf4j:slf4j-jdk14",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "ch.qos.logback:logback-classic",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        },
        {
            "module" : "ch.qos.logback:logback-core",
            "reason" : "Spring Boot Log4J 2 configuration",
            "author" : "Danny Thomas",
            "date" : "2018-10-30"
        }
    ],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-okhttp3.json
{
    "align": [
            {
                "name": "align-okhttp3",
                "group": "com\\.squareup\\.okhttp3.*",
                "includes": [],
                "excludes": ["okhttp-ws"],
                "reason": "Align okhttp3",
                "author": "Danny Thomas <dannyt@netflix.com>",
                "date": "2016-10-26"
            }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}
