=== nebula-plugins/gradle-resolution-rules/src/test/resources/valid-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "Resolution Rule",
  "description": "validation of resolution rules",
  "type": "object",
  "properties": {
    "align": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "group": {
            "type": "string"
          },
          "includes": {
            "type": "array"
          },
          "excludes": {
            "type": "array"
          },
          "match": {
            "type": "string"
          },
          "ruleSet": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          },
          "author": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        },
        "required": [
          "includes",
          "excludes",
          "reason",
          "author",
          "date",
          "group"
        ],
        "additionalProperties": false
      },
      "uniqueItems": true
    },
    "deny": {
      "type": "array"
    },
    "exclude": {
      "type": "array"
    },
    "reject": {
      "type": "array"
    },
    "replace": {
      "type": "array"
    },
    "substitute": {
      "type": "array"
    }
  },
  "required": [
    "align",
    "deny",
    "exclude",
    "reject",
    "replace",
    "substitute"
  ],
  "additionalProperties": false
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-ribbon.json
{
    "align": [
        {
            "name": "align-ribbon",
            "group": "com\\.netflix\\.ribbon",
            "includes": [],
            "excludes": ["ribbon-httpasyncclient"],
            "reason": "Align Ribbon libraries.",
            "author": "Danny Thomas <dannyt@netflix.com>",
            "date": "2016-05-31"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-xstream.json
{
    "align": [
            {
                "name": "align-xstream",
                "group": "com.thoughtworks.xstream",
                "match": "EXCLUDE_SUFFIXES",
                "reason": "Align all xstream libraries",
                "author": "Danny Thomas <dannyt@netflix.com>",
                "includes": [],
                "excludes": [],
                "date": "2016-05-15"
            }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/substitute-commons-configuration2.json
{
    "align": [],
    "deny": [],
    "exclude": [],
    "reject": [],
    "replace": [],
    "substitute": [
        {
            "module": "org.apache.commons:commons-configuration2:[2.2,2.7]",
            "with": "org.apache.commons:commons-configuration2:2.8.0",
            "reason": "The versions 2.2 to 2.7 of commons-configuration2 are vulnerable with CVE-2022-33980",
            "author": "mchalupa@netflix.com",
            "date": "2022-07-20"
        }
    ]
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-kotlin.json
{
    "align": [
            {
                "name": "align-kotlin",
                "group": "org.jetbrains.kotlin",
                "reason": "Align Kotlin libraries",
                "includes": [],
                "excludes": ["kotlin-(gradle-plugin-core|jdk-annotations|android-sdk-annotations|swing|jdbc|stdlib-validator|android-compiler-plugin|gradle-plugin-test|maven-plugin-test|build-common-test|stdlib-gen|js-tests-junit|js-tests|js-library|build-common)", "kdoc", "kdoc-maven-plugin", "kunit"],
                "author": "Danny Thomas <dannyt@netflix.com>",
                "date": "2016-06-14"
            }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "exclude": [],
    "reject": []
}

=== nebula-plugins/gradle-resolution-rules/src/main/resources/align-springfox.json
{
    "align": [
        {
            "name": "align-springfox",
            "group": "io.springfox",
            "includes": ["springfox-(bean-validators|core|schema|spi|spring-web|swagger-common|swagger-ui|swagger2|)"],
            "excludes": [],
            "reason": "Align Springfox libraries.",
            "author": "Remy Tiitre <remy.tiitre@lhv.ee>",
            "date": "2016-09-22"
        }
    ],
    "replace": [],
    "substitute": [],
    "deny": [],
    "reject": [],
    "exclude": []
}
